// Generated by CoffeeScript 1.9.2
(function() {
  var preloaded,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  preloaded = [];

  arcs.preload = function(images) {
    var i, img, len, results;
    if (typeof images === 'string') {
      images = [images];
    }
    results = [];
    for (i = 0, len = images.length; i < len; i++) {
      img = images[i];
      if (indexOf.call(preloaded, img) >= 0) {
        continue;
      }
      $('<img />').attr('src', img).hide().appendTo('body');
      results.push(preloaded.push(img));
    }
    return results;
  };

}).call(this);
