// Generated by CoffeeScript 1.10.0
(function() {
  if (!('open' in document.createElement('details'))) {
    document.documentElement.className += ' no-details';
  }

  $(function() {
    $('body').on('focus', 'input[placeholder]', function(e) {
      var $el;
      $el = $(e.currentTarget);
      if ($el.val() === $el.attr('placeholder')) {
        $el.val('');
        return $el.removeClass('unfocused');
      }
    });
    $('body').on('blur', 'input[placeholder]', function(e) {
      var $el;
      $el = $(e.currentTarget);
      if ($el.val() === '') {
        $el.val($el.attr('placeholder'));
        return $el.addClass('unfocused');
      }
    });
    $('body').tooltip({
      selector: '[rel=tooltip]'
    });
    $('body').popover({
      selector: '[rel=popover]'
    });
    return $('body').delegate('input[type="text"][id*="date"]', 'focus', function(e) {
      return $(e.currentTarget).datepicker({
        format: 'yyyy/mm/dd'
      });
    });
  });

}).call(this);

$(document).ready(function() {
  $("#registerModal .selectDiv").click(function() {
    $("#projectDropdown").toggle();
    var value = "";
    $("#projectDropdown .selected").each(function(i, e) {
      if (value == "") {
        value = $(e).attr("id");
      }
      else {
        value += ", " + $(e).attr("id");
      }
    });
    $("#UserProject").val(value);
  });

  $("#projectDropdown > p").click(function(e) {
    var target = $(e.target);
    var selectDiv = $(".selectDiv");
    target.toggleClass('selected');
    if (target.hasClass('selected')) {
      console.log(selectDiv.text());
      if (selectDiv.text().includes("Select Project(s) to Register In *")) {
        selectDiv.text(target.text());
      }
      else {
        selectDiv.text(selectDiv.text() + ", " + target.text());
      }
    }
    else {
      var temp = selectDiv.text();
      temp = temp.replace(", " + target.text, "");
      temp = temp.replace(target.text, "");
      selectDiv.text(temp);
    }
    if ($("#projectDropdown .selected").length == 0) {
      selectDiv.text("Select Project(s) to Register In *");
    }
  });
});
