// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  arcs.models.Bookmark = (function(superClass) {
    extend(Bookmark, superClass);

    function Bookmark() {
      return Bookmark.__super__.constructor.apply(this, arguments);
    }

    Bookmark.prototype.urlRoot = arcs.baseURL + 'bookmarks';

    return Bookmark;

  })(Backbone.Model);

}).call(this);
