// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  arcs.models.Collection = (function(superClass) {
    extend(Collection, superClass);

    Collection.prototype.defaults = {
      id: null,
      title: 'Temporary Collection',
      description: '',
      "public": false,
      members: []
    };

    function Collection(attributes) {
      Collection.__super__.constructor.call(this, this.parse(attributes));
    }

    Collection.prototype.urlRoot = arcs.baseURL + 'collections/add';

    Collection.prototype.parse = function(c) {
      var k, ref, v;
      if (c.Collection != null) {
        ref = c.Collection;
        for (k in ref) {
          v = ref[k];
          c[k] = v;
        }
        delete c.Collection;
      }
      return c;
    };

    return Collection;

  })(Backbone.Model);

}).call(this);
