// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  arcs.models.Flag = (function(superClass) {
    extend(Flag, superClass);

    Flag.prototype.urlRoot = arcs.baseURL + 'flags';

    function Flag(attributes) {
      Flag.__super__.constructor.call(this, this.parse(attributes));
    }

    Flag.prototype.parse = function(f) {
      var k, ref, v;
      if (f.Flag != null) {
        ref = f.Flag;
        for (k in ref) {
          v = ref[k];
          f[k] = v;
          delete f.Flag;
        }
        if (f.User != null) {
          f.user = f.User;
          delete f.User;
        }
        if (f.Resource != null) {
          f.resource = f.Resource;
          delete f.Resource;
        }
      }
      return f;
    };

    return Flag;

  })(Backbone.Model);

}).call(this);
