// Generated by CoffeeScript 1.9.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  arcs.models.MetadataContainer = (function(superClass) {
    extend(MetadataContainer, superClass);

    function MetadataContainer() {
      return MetadataContainer.__super__.constructor.apply(this, arguments);
    }

    MetadataContainer.prototype.url = function() {
      return arcs.baseURL + 'resources/metadata/' + this.id;
    };

    return MetadataContainer;

  })(Backbone.Model);

}).call(this);
