// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  arcs.collections.AnnotationList = (function(superClass) {
    extend(AnnotationList, superClass);

    function AnnotationList() {
      return AnnotationList.__super__.constructor.apply(this, arguments);
    }

    AnnotationList.prototype.model = arcs.models.Annotation;

    AnnotationList.prototype.url = function() {
      return arcs.baseURL + "resources/annotations/" + arcs.resource.id;
    };

    AnnotationList.prototype.parse = function(r) {
      if (r.relations != null) {
        this.relations = new arcs.collections.Collection(r.relations);
      }
      return r.annotations;
    };

    return AnnotationList;

  })(Backbone.Collection);

}).call(this);
