// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  arcs.collections.CollectionList = (function(superClass) {
    extend(CollectionList, superClass);

    function CollectionList() {
      return CollectionList.__super__.constructor.apply(this, arguments);
    }

    CollectionList.prototype.model = arcs.models.Collection;

    CollectionList.prototype.initialize = function() {
      return this.sortVar = 'created';
    };

    CollectionList.prototype.comparator = function(resource) {
      return resource.get(this.sortVar);
    };

    return CollectionList;

  })(Backbone.Collection);

}).call(this);
