// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  arcs.collections.Discussion = (function(superClass) {
    extend(Discussion, superClass);

    function Discussion() {
      return Discussion.__super__.constructor.apply(this, arguments);
    }

    Discussion.prototype.model = arcs.models.Comment;

    Discussion.prototype.url = function() {
      return arcs.baseURL + "resources/comments/" + arcs.resource.id;
    };

    Discussion.prototype.parse = function(response) {
      var i, len, r, results;
      results = [];
      for (i = 0, len = response.length; i < len; i++) {
        r = response[i];
        results.push(_.extend(r.User, r.Comment));
      }
      return results;
    };

    return Discussion;

  })(Backbone.Collection);

}).call(this);
