// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  arcs.collections.FlagList = (function(superClass) {
    extend(FlagList, superClass);

    function FlagList() {
      return FlagList.__super__.constructor.apply(this, arguments);
    }

    FlagList.prototype.model = arcs.models.Flag;

    FlagList.prototype.url = function() {
      return arcs.baseURL + "resources/flags/" + arcs.resource.id;
    };

    FlagList.prototype.parse = function(response) {
      var i, len, r, results;
      results = [];
      for (i = 0, len = response.length; i < len; i++) {
        r = response[i];
        results.push(r.Flag);
      }
      return results;
    };

    return FlagList;

  })(Backbone.Collection);

}).call(this);
