// Generated by CoffeeScript 1.9.2
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  arcs.collections.JobList = (function(superClass) {
    extend(JobList, superClass);

    function JobList() {
      return JobList.__super__.constructor.apply(this, arguments);
    }

    JobList.prototype.model = arcs.models.Job;

    return JobList;

  })(Backbone.Collection);

}).call(this);
