// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  arcs.collections.UserList = (function(superClass) {
    extend(UserList, superClass);

    function UserList() {
      return UserList.__super__.constructor.apply(this, arguments);
    }

    UserList.prototype.model = arcs.models.User;

    return UserList;

  })(Backbone.Collection);

}).call(this);
