// Generated by CoffeeScript 1.10.0
(function() {
  describe('arcs', function() {
    it('can log', function() {
      return expect(arcs.log).toBeDefined();
    });
    return it('can bind events', function() {
      var triggered;
      triggered = false;
      arcs.bind('testBind', (function(_this) {
        return function() {
          return triggered = true;
        };
      })(this));
      arcs.trigger('testBind');
      return expect(triggered).toBe(true);
    });
  });

}).call(this);
