// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  arcs.routers.Viewer = (function(superClass) {
    extend(Viewer, superClass);

    function Viewer() {
      return Viewer.__super__.constructor.apply(this, arguments);
    }

    Viewer.prototype.routes = {
      ':id': 'noIndex',
      ':id/': 'noIndex',
      ':id/:index': 'indexChange'
    };

    Viewer.prototype.noIndex = function(id) {
      arcs.bus.trigger('indexChange', 0);
      return {
        noNavigate: true,
        replace: true
      };
    };

    Viewer.prototype.indexChange = function(id, index) {
      if (_.isNumeric(index)) {
        index -= 1;
      }
      return arcs.bus.trigger('indexChange', index, {
        noNavigate: true
      });
    };

    return Viewer;

  })(Backbone.Router);

}).call(this);
