// Generated by CoffeeScript 1.10.0
(function() {
  var base, display, selected, selectedCount, selectedMap, totalResults, waiting,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  selectedMap = {
    "unselected": [],
    "selected": []
  };

  selectedCount = 0;

  selected = [];

  display = [];

  totalResults = [];

  waiting = false;

  if ((base = arcs.views).search == null) {
    base.search = {};
  }

  arcs.views.search.Search = (function(superClass) {
    var adjustPage, fillArray, get_filter_fields, noResults, pagination, search, showSelected;

    extend(Search, superClass);

    function Search() {
      return Search.__super__.constructor.apply(this, arguments);
    }

    Search.prototype.options = {
      sort: 'title',
      sortDir: 'asc',
      grid: true,
      url: arcs.baseURL + 'search/'
    };


    /* Initialize and define events */

    Search.prototype.initialize = function(options) {
      _.extend(this.options, _.pick(options, 'el'));
      this.setupSelect();
      this.setupSearch();
      Backbone.history.start({
        pushState: true,
        root: this.options.url
      });
      this.search.results.on('change remove', this.render, this);
      arcs.bus.on('selection', this.afterSelection, this);
      arcs.keys.map(this, {
        'ctrl+a': this.selectAll,
        '?': this.showHotkeys,
        t: this.scrollTop
      });
      return this.setupHelp();
    };

    Search.prototype.events = {
      'click #grid-btn': 'toggleView',
      'click #list-btn': 'toggleView',
      'click #top-btn': 'scrollTop',
      'click .dir-btn': 'setSortDir',
      'click .search-page-btn': 'setPage',
      'click .search-type': 'addFacet',
      'click .pageNumber': 'scrollTop',
      'click #leftArrowBox': 'scrollTop',
      'click #rightArrowBox': 'scrollTop',
      'click .sort-btn': 'scrollTop',
      'click .fDots': 'scrollTop',
      'click .dots': 'scrollTop'
    };


    /* More involved setups run by the initialize method */

    Search.prototype.setupSelect = function() {
      return this.$el.find('#search-results').selectable({
        distance: 20,
        filter: '.img-wrapper img',
        selecting: (function(_this) {
          return function(e, ui) {
            $(ui.selecting).parents('.result').addClass('selected');
            $(ui.selecting).parents('.result').children('.select-button').html('DE-SELECT');
            $(ui.selecting).parents('.result').children('.select-button').addClass('de-select');
            return _this.afterSelection();
          };
        })(this),
        selected: (function(_this) {
          return function(e, ui) {
            $(ui.selected).parents('.result').addClass('selected');
            $(ui.selected).parents('.result').children('.select-button').html('DE-SELECT');
            $(ui.selected).parents('.result').children('.select-button').addClass('de-select');
            return _this.afterSelection();
          };
        })(this),
        unselecting: (function(_this) {
          return function(e, ui) {
            $(ui.unselecting).parents('.result').removeClass('selected');
            $(ui.unselecting).parents('.result').children('.select-button').html('SELECT');
            $(ui.unselecting).parents('.result').children('.select-button').removeClass('de-select');
            return _this.afterSelection();
          };
        })(this),
        unselected: (function(_this) {
          return function(e, ui) {
            $(ui.unselected).parents('.result').removeClass('selected');
            $(ui.unselected).parents('.result').children('.select-button').html('SELECT');
            $(ui.unselected).parents('.result').children('.select-button').removeClass('de-select');
            return _this.afterSelection();
          };
        })(this)
      });
    };

    Search.prototype.setupSearch = function() {
      this.scrollReady = false;
      return this.search = new arcs.utils.Search({
        container: $('searchBox'),
        order: this.options.sort,
        run: false,
        loader: true,
        success: (function(_this) {
          return function() {
            _this.router.navigate((encodeURIComponent(_this.search.query)) + "/p" + _this.search.page);
            if (!_this.scrollReady) {
              _this.setupScroll() && (_this.scrollReady = true);
            }
            _this.setupHelp();
            return _this.render();
          };
        })(this)
      });
    };

    Search.prototype.setupScroll = function() {
      var $actions, $results, $window, pos, ref;
      ref = [this.$('#search-actions'), this.$('#search-results')], $actions = ref[0], $results = ref[1];
      $window = $(window);
      pos = $actions.offset().top - 10;
      return $window.resize(function() {
        if ($window.scrollTop() > pos) {
          return $actions.width($results.width() + 23);
        }
      });
    };

    Search.prototype.setupHelp = function() {
      if (!$('.search-help-btn').length) {
        $('.VS-search-inner').append(arcs.tmpl('search/help-toggle'));
        $('.search-help-btn').click(this.showHelp);
        return $('.search-help-close').click(this.closeHelp);
      }
    };

    Search.prototype.toggleView = function() {
      this.options.grid = !this.options.grid;
      this.$('#grid-btn').toggleClass('active');
      this.$('#list-btn').toggleClass('active');
      return this.render();
    };

    Search.prototype.scrollTop = function() {
      var time;
      time = ($(window).scrollTop() / $(document).height()) * 1000;
      return $('html, body').animate({
        scrollTop: 0
      }, time);
    };

    Search.prototype.setSort = function(e) {
      this.options.sort = e.target.id.match(/sort-(\w+)-btn/)[1];
      this.$('.sort-btn .icon-ok').remove();
      this.$(e.target).append(this.make('i', {
        "class": 'icon-ok'
      }));
      this.$('#sort-btn span#sort-by').html(this.options.sort);
      return this.search.run(null, {
        order: this.options.sort,
        direction: this.options.sortDir
      });
    };

    Search.prototype.setSortDir = function(e) {
      this.options.sortDir = e.target.id.match(/dir-(\w+)-btn/)[1];
      this.$('.dir-btn .icon-ok').remove();
      this.$(e.target).append(this.make('i', {
        "class": 'icon-ok'
      }));
      return this.search.run(null, {
        order: this.options.sort,
        direction: this.options.sortDir
      });
    };

    Search.prototype.setPage = function(e) {
      e.preventDefault();
      this.$el = $(e.currentTarget);
      this.search.options.page = this.$el.data('pageNumber');
      return this.search.run();
    };

    Search.prototype.unselectAll = function(trigger) {
      if (trigger == null) {
        trigger = true;
      }
      this.$('.result').removeClass('selected');
      this.$('.select-button').removeClass('de-select');
      this.$('.select-button, #toggle-select').html('SELECT');
      this.$('#deselect-all').attr({
        id: 'select-all'
      });
      if (trigger) {
        return arcs.bus.trigger('selection');
      }
    };

    Search.prototype.selectAll = function(trigger) {
      if (trigger == null) {
        trigger = true;
      }
      this.$('.result').addClass('selected');
      this.$('.select-button').addClass('de-select');
      this.$('.select-button, #toggle-select').html('DE-SELECT');
      this.$('#select-all').attr({
        id: 'deselect-all'
      });
      if (trigger) {
        return arcs.bus.trigger('selection');
      }
    };

    Search.prototype.toggle = function(e) {
      if (!(e.ctrlKey || e.shiftKey || e.metaKey)) {
        this.unselectAll(false);
      }
      $(e.currentTarget).parents('.result').toggleClass('selected');
      return arcs.bus.trigger('selection');
    };

    Search.prototype.maybeUnselectAll = function(e) {
      if (!(e instanceof jQuery.Event)) {
        return this.unselectAll();
      }
      if (e.metaKey || e.ctrlKey || e.shiftKey) {
        return false;
      }
      if ($(e.target).attr('src')) {
        return false;
      }
      return this.unselectAll();
    };

    Search.prototype.showHotkeys = function() {
      if ($('.hotkeys-modal').length) {
        return $('.hotkeys-modal').remove();
      }
      return new arcs.views.Hotkeys({
        template: 'search/hotkeys'
      });
    };

    Search.prototype.showHelp = function() {
      return $('.search-help').show();
    };

    Search.prototype.closeHelp = function() {
      return $('.search-help').hide();
    };


    /* Render the search results */

    $('.dropdown-menu').change(function(event) {});

    Search.prototype.append = function() {
      var results;
      if (!(this.search.results.length > this.search.options.n)) {
        return;
      }
      results = new arcs.collections.ResultSet(this.search.getLast());
      return this._render({
        results: results.toJSON()
      }, true);
    };

    Search.prototype.addFacet = function(e) {
      e.preventDefault();
      return this.search.vs.searchBox.addFacet(e.target.text, '', 10);
    };

    fillArray = function(page, lastPage) {
      var i, results1;
      if (page < 3) {
        page = 3;
      }
      if (page === lastPage) {
        page = page - 2;
      }
      if (page === lastPage - 1) {
        page = page - 1;
      }
      i = -1;
      results1 = [];
      while (i < 4) {
        i++;
        if ((page + (i - 2)) <= lastPage) {
          results1.push(page + (i - 2));
        } else {
          results1.push(0);
        }
      }
      return results1;
    };

    pagination = function(pageArray, currentPage, lastPage) {
      var i, j, results1;
      if (indexOf.call(pageArray, 1) >= 0) {
        $('#firstPage').css('display', 'none');
        $('.fDots').css('display', 'none');
      } else {
        $('#firstPage').css('display', 'block');
        $('.fDots').css('display', 'block');
      }
      if (1 === currentPage) {
        $('#rightArrow').css('display', 'none');
      } else {
        $('#rightArrow').css('display', 'block');
      }
      if (indexOf.call(pageArray, lastPage) >= 0) {
        $('#lastPage').css('display', 'none');
        $('.dots').css('display', 'none');
        $('#leftArrow').css('display', 'none');
      } else {
        $('#lastPage').css('display', 'block');
        $('.dots').css('display', 'block');
        $('#leftArrow').css('display', 'block');
      }
      if (currentPage === lastPage) {
        $('#lefttArrow').css('display', 'none');
      } else {
        $('#leftArrow').css('display', 'block');
      }
      if (2 === pageArray[0]) {
        $('.fDots').css('display', 'none');
      }
      if (lastPage - 1 === pageArray[4]) {
        $('.dots').css('display', 'none');
      }
      results1 = [];
      for (i = j = 1; j <= 5; i = ++j) {
        if (pageArray[i - 1] <= 0) {
          results1.push($('#' + i).css('display', 'none'));
        } else {
          $('#' + i).css('display', 'block');
          $('#' + i).html(pageArray[i - 1]);
          if (parseInt($('#' + i).html()) === currentPage) {
            $('#' + i).addClass('selected');
            results1.push($('#' + i).addClass('currentPage'));
          } else {
            results1.push(void 0);
          }
        }
      }
      return results1;
    };

    noResults = function() {
      var i, j, results1;
      $('#firstPage').css('display', 'none');
      $('.fDots').css('display', 'none');
      $('#lastPage').css('display', 'none');
      $('.dots').css('display', 'none');
      $('#leftArrow').css('display', 'none');
      $('#rightArrow').css('display', 'none');
      results1 = [];
      for (i = j = 1; j <= 5; i = ++j) {
        results1.push($('#' + i).css('display', 'none'));
      }
      return results1;
    };

    showSelected = function() {
      return $('.result').each(function() {
        var ref;
        if (ref = $(this).data('id'), indexOf.call(selectedMap['selected'], ref) >= 0) {
          $(this).addClass('selected');
          $(this).find('.select-button').addClass('de-select');
          return $(this).find('.select-button').html('DE-SELECT');
        }
      });
    };

    adjustPage = function(results, currentPage) {
      var lastPage, numberPerPage, pageNum, skip, temp;
      if (waiting) {
        return;
      }
      $('.pageNumber').removeClass('currentPage');
      $('.pageNumber').removeClass('selected');
      pageNum = currentPage;
      numberPerPage = parseInt($('#items-per-page-btn').html().substring(0, 2));
      lastPage = Math.ceil(results.length / numberPerPage);
      temp = fillArray(pageNum, lastPage);
      pagination(temp, pageNum, lastPage);
      skip = (pageNum - 1) * numberPerPage;
      $('#lastPage').html(lastPage);
      Search.prototype._render({
        results: totalResults.slice(skip, skip + numberPerPage)
      });
      if (selectedMap['selected'].length > 0) {
        return showSelected();
      }
    };

    search = function() {
      var pageNum, pageNumber, perPage, perPageUrl, resourcequery, val, wiating;
      wiating = true;
      val = $(".searchBoxInput").val();
      pageNum = $('.currentPage').html();
      perPage = $('#items-per-page-btn').html().substring(0, 2);
      if (val === "") {
        noResults();
        totalResults = [];
        Search.prototype._render({
          results: totalResults
        });
        return;
      }
      resourcequery = encodeURIComponent("" + val);
      pageNumber = encodeURIComponent("" + pageNum);
      perPageUrl = encodeURIComponent("" + perPage);
      $('.pageNumber').removeClass('currentPage');
      $('.pageNumber').removeClass('selected');
      totalResults = [];
      return $.ajax({
        'dataType': 'json',
        'url': arcs.baseURL + 'simple_search/' + resourcequery + "/" + pageNumber + "/" + perPageUrl,
        'success': function(data) {
          var key, ref, value;
          if (data['total'] === 0) {
            adjustPage([], 0);
            return noResults();
          } else {
            console.log(data);
            get_filter_fields(data['resutls']);
            $('#results-count').html(data['total']);
            ref = data['results'];
            for (key in ref) {
              value = ref[key];
              totalResults.push(value);
              selectedMap['unselected'].push(value['kid']);
            }
            selectedMap['unselected'] = totalResults;
            waiting = false;
            return adjustPage(totalResults, 1);
          }
        }
      });
    };

    get_filter_fields = function(arr) {
      var creators, excavations, results1, seasons, sites;
      sites = new array();
      seasons = new array();
      excavations = new array();
      creators = new array();
      results1 = [];
      while (i < arr.length) {
        seasons[arr['Season Title']] = arr['Season Title'];
        excavations[arr['Excavation - Survey Name']] = arr['Excavation - Survey Name'];
        creators[arr['Creator']] = arr['Creator'];
        results1.push(i++);
      }
      return results1;
    };

    $(function() {
      return $(".searchBoxInput").keyup(function(e) {
        if (e.keyCode === 13) {
          selectedMap = {
            "unselected": [],
            "selected": []
          };
          $('.pageNumber').removeClass('selected');
          $('.pageNumber').removeClass('currentPage');
          $("#1").addClass('selected');
          $("#1").addClass('currentPage');
          $("#1").html(1);
          e.preventDefault();
          $('.flex-container').empty();
          $('.flex-container').append('<img src="/~arnold.mutayoba/arcs/img/arcs-preloader.gif">');
          $('#search-results-wrapper').css('visibility', 'visible');
          return search();
        }
      });
    });

    Search.prototype._render = function(results, append) {
      var $results, template;
      if (append == null) {
        append = false;
      }
      $results = $('.flex-container');
      template = this.options.grid ? 'search/grid' : 'search/list';
      results = results.results;
      $results[append ? 'append' : 'html'](arcs.tmpl(template, {
        results: results
      }));
      $(".pageNumber").unbind().click(function(e) {
        if ($(this).hasClass('selected')) {
          e.stopPropagation();
        } else {
          $('.pageNumber').removeClass('selected');
          $('.pageNumber').removeClass('currentPage');
          $(this).addClass('selected');
          $(this).addClass('currentPage');
          adjustPage(totalResults, parseInt($('.currentPage').html()));
        }
      });
      $('#leftArrowBox').unbind().click(function(e) {
        var temp;
        temp = $('.currentPage').html();
        $('.currentPage').html(parseInt(temp) + 1);
        return adjustPage(totalResults, parseInt($('.currentPage').html()));
      });
      $('#rightArrowBox').unbind().click(function(e) {
        var temp;
        temp = $('.currentPage').html();
        if (temp === '1') {

        } else {
          $('.currentPage').html(parseInt(temp) - 1);
          return adjustPage(totalResults, parseInt($('.currentPage').html()));
        }
      });
      $('#dots').unbind().click(function() {
        var temp;
        temp = parseInt($('.currentPage').html()) + 5;
        if (temp > parseInt($("#lastPage").html())) {
          temp = parseInt($("#lastPage").html());
        }
        $('.currentPage').html(temp);
        return adjustPage(totalResults, parseInt($('.currentPage').html()));
      });
      $('#fDots').unbind().click(function() {
        var temp;
        temp = parseInt($('.currentPage').html()) - 5;
        if (temp < 1) {
          temp = 1;
        }
        $('.currentPage').html(temp);
        return adjustPage(totalResults, parseInt($('.currentPage').html()));
      });
      $('div.result').hover((function() {
        $(this).find('.select-button').show();
        $(this).find('img').addClass('img-hover');
      }), function() {
        $(this).find('.select-button').hide();
        $(this).find('img').removeClass('img-hover');
      });
      $('.select-button').click(function() {
        var index;
        if ($(this).html() === 'SELECT') {
          $(this).html('DE-SELECT');
          $(this).addClass('de-select');
          $(this).parents('.result').addClass('selected');
          $('#selected-all').css({
            color: 'black'
          });
          selectedMap['selected'].push($(this).parents('.result').data("id"));
          $('#selected-resource-ids').html(selectedMap["selected"]);
          $('#selected-count').html(selectedMap["selected"].length);
          arcs.bus.trigger('selection');
        } else {
          $(this).html('SELECT');
          $(this).removeClass('de-select');
          $(this).parents('.result').removeClass('selected');
          index = selectedMap['selected'].indexOf($(this).parents('.result').data("id"));
          if (index > -1) {
            selectedMap['selected'].splice(index, 1);
          }
          if (selectedMap['selected'].length < 1) {
            $('#selected-all').css({
              color: '#C1C1C1'
            });
          }
          $('#selected-resource-ids').html(selectedMap["selected"]);
          $('#selected-count').html(selectedMap["selected"].length);
          arcs.bus.trigger('selection');
        }
      });
      $('.sort-btn').unbind().click(function() {
        $('#items-per-page-btn').html($(this).html() + "<span class='pointerDown sort-arrow pointerSearch'></span>");
        $('.pageNumber').removeClass('selected');
        $('.pageNumber').removeClass('currentPage');
        $("#1").addClass('selected');
        $("#1").addClass('currentPage');
        $("#1").html(1);
        return adjustPage(totalResults, parseInt($('.currentPage').html()));
      });
      $('#select-all, #deselect-all').unbind().click(function() {
        var i;
        if (this.id === 'select-all') {
          $('#selected-all').css({
            color: 'black'
          });
          selectedMap['selected'] = [];
          i = 0;
          for (i in totalResults) {
            selectedMap['selected'].push(totalResults[i]['kid']);
            ++i;
          }
          arcs.searchView.selectAll();
          $('#toggle-select').html('DE-SELECT');
          $('#selected-resource-ids').html(selectedMap["selected"]);
          return $('#selected-count').html(selectedMap["selected"].length);
        } else {
          $('#selected-all').css({
            color: '#C1C1C1'
          });
          selectedMap['selected'] = [];
          this.id = 'select-all';
          arcs.searchView.unselectAll();
          $('#selected-resource-ids').html(selectedMap["selected"]);
          return $('#selected-count').html(selectedMap["selected"].length);
        }
      });
      if (results.length === 0) {
        return $results.html("<div id='no-results'>No Results</div>");
      }
    };

    return Search;

  })(Backbone.View);

}).call(this);
