// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  arcs.views.Home = (function(superClass) {
    extend(Home, superClass);

    function Home() {
      return Home.__super__.constructor.apply(this, arguments);
    }

    Home.prototype.initialize = function(options) {
      _.extend(this.options, _.pick(options, "el"));
      this.search = new arcs.utils.Search({
        container: $('.search-wrapper'),
        run: false,
        onSearch: (function(_this) {
          return function() {
            return location.href = arcs.url('search', _this.search.query);
          };
        })(this)
      });
      return $('details:first').children().eq(0).trigger("click");
    };

    Home.prototype.events = {
      'click summary': 'onClick',
      'click .btn-show-all': 'onClick'
    };

    Home.prototype.onClick = function(e) {
      var $el, limit, src;
      if (e.currentTarget.tagName === 'SUMMARY') {
        $el = $(e.currentTarget).parent();
        if ($el[0].hasAttribute("open")) {
          $el.children('div').html('');
          return;
        }
        $el.toggleAttr('open');
        limit = 25;
        src = arcs.baseURL + 'img/arcs-preloader.gif';
        if ($(e.currentTarget).next().children().eq(0).prop("tagName") !== 'IMG') {
          $(e.currentTarget).next().prepend('<img src="' + src + '" alt="SeeAll.svg">');
        }
      } else if (e.currentTarget.className === 'btn-show-all') {
        $el = $(e.currentTarget).parent().parent().parent().parent();
        $(e.currentTarget).removeClass('btn-show-all');
        src = arcs.baseURL + 'img/arcs-preloader.gif';
        $(e.currentTarget).find("img:first").attr('src', src);
        //limit = $el.find('.resource-thumb').length + 14;
        limit = -1;
        //console.log('resources show more redirect here');
        //return;
      } else {
        $el = $(e.currentTarget).parent();
        $el.toggleAttr('open');
        limit = 0;
      }
      this.renderDetails($el, limit);
      e.preventDefault();
      return false;
    };

    //the resources page. where the ajax for drawers is.
    Home.prototype.renderDetails = function($el, limit) {
      var query, query2, type;
      type = $el.data('type');
      query = encodeURIComponent("Type,=," + type);
      if (type === 'Orphaned') {
        query = encodeURIComponent('Orphan,=,true') + '&sid=' + arcs.pagesSid;
      }
      query2 = arcs.baseURL + 'resources/search?';
      if (limit !== 0) {
        query2 += "n=" + limit + "&";
      }
      var url = window.location.href.split('/');
      var kid = '';
      kid = url.pop();
      if(kid != '' && kid != 'resources' ){
        query2 += "pKid=" + kid + "&";
      }
      return $.getJSON(query2 + ("q=" + query), function(response) {
        if(typeof response.results[0] == "object" ){
          var html;
          html = arcs.tmpl('home/details', {
            resources: response.results,
            searchURL: arcs.baseURL + "collection/"
          });
          $el.children('div').html(html);
          return; //$el.find('.show-all-btn-text').html('SHOW MORE');
        }else {
          if (type === 'Orphaned') {
            $('<form />')
                .hide()
                .attr({ method : "post" })
                .attr({ action : "../search/collection"})
                .append($('<input />')
                    .attr("type","hidden")
                    .attr({ "name" : "orphaned_kids" })
                    .val(response.results)
                )
                .append('<input type="submit" />')
                .appendTo($("body"))
                .submit();
          }else {
            $('<form />')
                .hide()
                .attr({method: "post"})
                .attr({action: "../search/collection"})
                .append($('<input />')
                    .attr("type", "hidden")
                    .attr({"name": "resource_kids"})
                    .val(response.results)
                )
                .append('<input type="submit" />')
                .appendTo($("body"))
                .submit();
          }
          return;
        }
      });
    };

    return Home;

  })(Backbone.View);

}).call(this);
