// Generated by CoffeeScript 1.10.0
(function() {
    var base,
        extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
        hasProp = {}.hasOwnProperty;

    if ((base = arcs.views).admin == null) {
        base.admin = {};
    }

    arcs.views.admin.Activity = (function(superClass) {
        extend(Activity, superClass);

        function Activity() {
            return Activity.__super__.constructor.apply(this, arguments);
        }

        Activity.prototype.initialize = function(options) {
            _.extend(this.options, _.pick(options, 'el', 'collection'));
            this.collection.on('add remove change sync', this.render, this);
            return this.render();
        };

        Activity.prototype.render = function() {
            this.$('#activity').html(arcs.tmpl('admin/activity', {
                activity: this.collection.toJSON()
            }));
            return this;
        };

        return Activity;

    })(Backbone.View);

}).call(this);
