// Generated by CoffeeScript 1.9.3
(function() {
  var base,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  if ((base = arcs.views).admin == null) {
    base.admin = {};
  }

  arcs.views.admin.Flags = (function(superClass) {
    extend(Flags, superClass);

    function Flags() {
      return Flags.__super__.constructor.apply(this, arguments);
    }

    Flags.prototype.initialize = function() {
      this.collection.on('add remove change sync', this.render, this);
      return this.render();
    };

    Flags.prototype.render = function() {
      this.$('#flags').html(arcs.tmpl('admin/flags', {
        flags: this.collection.toJSON()
      }));
      return this;
    };

    return Flags;

  })(Backbone.View);

}).call(this);
