// Generated by CoffeeScript 1.10.0
(function() {
  var base,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  if ((base = arcs.views).admin == null) {
    base.admin = {};
  }

  arcs.views.admin.Metadata_edits = (function(superClass) {
    extend(Metadata_edits, superClass);

    function Metadata_edits() {
      return Metadata_edits.__super__.constructor.apply(this, arguments);
    }

      Metadata_edits.prototype.initialize = function(options) {
      _.extend(this.options, _.pick(options, 'el', 'collection'));
      this.collection.on('add remove change sync', this.render, this);
      return this.render();
    };

      Metadata_edits.prototype.render = function() {
      this.$('#metadata_edits').html(arcs.tmpl('admin/metadata_edits', {
          metadata_edits: this.collection.toJSON()
      }));
      return this;
    };

    return Metadata_edits;

  })(Backbone.View);

}).call(this);
