// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  arcs.views.DiscussionTab = (function(superClass) {
    extend(DiscussionTab, superClass);

    function DiscussionTab() {
      return DiscussionTab.__super__.constructor.apply(this, arguments);
    }

    DiscussionTab.prototype.events = {
      'click #comment-btn': 'saveComment'
    };

    DiscussionTab.prototype.initialize = function(options) {
      _.extend(this.options, _.pick(options, 'el'));
      this.collection = new arcs.collections.Discussion;
      this.collection.on('add remove reset', this.render, this);
      this.$tab = $('#discussion-btn');
      this.$tab.on('click', (function(_this) {
        return function() {
          return _this.update();
        };
      })(this));
      arcs.bus.on('indexChange', (function(_this) {
        return function() {
          if (_this.isActive()) {
            return _this.update();
          }
        };
      })(this));
      if (this.isActive()) {
        return this.update();
      }
    };

    DiscussionTab.prototype.activate = function() {
      $('#discussion-btn a').tab('show');
      return this.collection.fetch();
    };

    DiscussionTab.prototype.update = function() {
      this.$el.parent().css('opacity', '0.2');
      return this.collection.fetch({
        success: (function(_this) {
          return function() {
            return _this.$el.parent().css('opacity', '1.0');
          };
        })(this),
        error: function() {
          return arcs.notify('An error occurred while loading comments', 'error');
        }
      });
    };

    DiscussionTab.prototype.isActive = function() {
      return $('#discussion-btn').hasClass('active');
    };

    DiscussionTab.prototype.saveComment = function() {
      var $textarea, comment;
      $textarea = this.$el.find('textarea#content');
      if (!$textarea.val()) {
        return arcs.notify('Enter a comment.');
      }
      comment = new arcs.models.Comment({
        resource_id: arcs.resource.id,
        content: $textarea.val()
      });
      $textarea.val('');
      comment.save();
      comment.set({
        created: new Date,
        username: arcs.user.get('username'),
        name: arcs.user.get('name')
      });
      return this.collection.add(comment);
    };

    DiscussionTab.prototype.render = function() {
      $('#comment-wrapper').html(arcs.tmpl('viewer/discussion', {
        comments: this.collection.toJSON()
      }));
      return this;
    };

    return DiscussionTab;

  })(Backbone.View);

}).call(this);
